// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6C57fiWSJQSRfHhocbgauC1yB7anMV9Q',
    appId: '1:990609359779:web:bb013cd86d38b874a6d016',
    messagingSenderId: '990609359779',
    projectId: 'attendance-210cd',
    authDomain: 'attendance-210cd.firebaseapp.com',
    databaseURL: 'https://attendance-210cd-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-210cd.appspot.com',
    measurementId: 'G-YF38EKHNND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2yTOC7htviDZMb-1zJKZEoTQHoqWo_4',
    appId: '1:990609359779:android:090ba0d5b1947465a6d016',
    messagingSenderId: '990609359779',
    projectId: 'attendance-210cd',
    databaseURL: 'https://attendance-210cd-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-210cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_jtd1wOaT9iG-PBUFJHFbtjuhSXch3M',
    appId: '1:990609359779:ios:f90c32b818976624a6d016',
    messagingSenderId: '990609359779',
    projectId: 'attendance-210cd',
    databaseURL: 'https://attendance-210cd-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-210cd.appspot.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu_jtd1wOaT9iG-PBUFJHFbtjuhSXch3M',
    appId: '1:990609359779:ios:f90c32b818976624a6d016',
    messagingSenderId: '990609359779',
    projectId: 'attendance-210cd',
    databaseURL: 'https://attendance-210cd-default-rtdb.firebaseio.com',
    storageBucket: 'attendance-210cd.appspot.com',
    iosBundleId: 'com.example.flutterLoginSignup',
  );
}
